### ISSUE TITLE
[Cisco ASA] The nat syntax is described outside the object network.

### ISSUE THREAD

**Issue by Katsuya414** [batfish/batfish#8335] opened 2022-05-25 12:17 UTC
Config syntax can be processed if the nat syntax is described inside the object network, but not if the nat syntax is described outside the object network.

object network INSIDE_LOCAL
 host 10.0.12.1
!
object network INSIDE_GLOBAL
  host 10.0.34.1
!
object network OUTSIDE_LOCAL
 host 10.0.45.5
!
object network OUTSIDE_GLOBAL
 host 10.0.23.1
!
nat (inside,outside) source static INSIDE_LOCAL INSIDE_GLOBAL destination static OUTSIDE_GLOBAL OUTSIDE_LOCAL

Also, here is a Traceroute run on Batfish
[ASA_NAT.zip](https://github.com/batfish/batfish/files/8770977/ASA_NAT.zip)
Here is the config of the device actually used
[ASA_NAT_configs.zip](https://github.com/batfish/batfish/files/8771000/ASA_NAT_configs.zip)

**Comment by dhalperi** [comment] 2022-07-14 07:15
@anothermattbrown - do you understand / can you quickly refresh on https://github.com/batfish/batfish/issues/3005 ?

**Comment by dhalperi** [comment] 2022-07-14 07:15
cc: @corinaminer

**Comment by dhalperi** [comment] 2022-09-07 02:29
This issue is a duplicate of #3005. No PR will be considered that does not solve a substantial fraction of the issues in #3005.

Especially including correctly handling multiple NAT rules that may conflict if not properly matched against original flow.

And note that this needs to work with *multiple chained firewalls*. That is, it cannot be "original flow" in a traceroute, but only "original flow" at the current firewall.

**Closed by dhalperi** 2022-09-07 02:29 UTC
